server:
  port: 5000

springdoc:
  swagger-ui:
    path: "/docs-ui"
    try-it-out-enabled: true
#    operations-sorter: "method"

  api-docs:
    path: "/docs"

#  packages-to-scan: "com.tallninja.springopenapi.controller"

app:
  openapi:
    info:
      title: "Spring OpenAPI"
      description: "Spring integration with OpenAPI 3"
      version: "1.0.0"
    server:
      dev-url: http://localhost:5000
      prod-url: http://springopenapi.tallninja.com
    contact:
      name: "Ernest Wambua"
      email: "ernestwambua2@gmail.com"
      url: "https://tallninja.github.io"
    license:
      name: "MIT License"
      url: "https://choosealicense.com/licenses/mit/"

