server:
  port: 5000

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/appdb'
    username: 'dbuser'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    show-sql: true
  graphql:
    graphiql:
      enabled: true
    schema:
      file-extensions: '.gql'
  artemis:
    broker-url: 'tcp://localhost:61616'
    user: 'admin'
    password: 'admin'