services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=appdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - '5672:5672'
      - '61616:61616'
    environment:
      AMQ_USER: 'admin'
      AMQ_PASSWORD: 'admin'
    volumes:
      - ./artemis/broker.xml:/opt/amq/conf/broker.xml
