services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=appdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
