services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - '5672:5672'
      - '61616:61616'
    environment:
      AMQ_USER: 'admin'
      AMQ_PASSWORD: 'admin'
    volumes:
      - ./broker/broker.xml:/opt/amq/conf/broker.xml